const { Router } = require('express')
const userRouter = require('./user.route')
const requestRouter = require('./request.route')
const clientRouter = require('./client.route')
const productRouter = require('./product.route')
const bakingRouter = require('./baking.route')
const salesRouter = require('./sales.route')
const bakingFacilityUnitsRouter = require('./bakeryFacilityUnits.route')
const dispatchRouter = require('./dispatch.route')
const individualPrices = require('./individualPrices.route')
const finance = require('./finance.route')
const financeCategories = require('./financeCategories.route')
let router = Router()

router.use('/user', userRouter)
router.use('/requests', requestRouter)
router.use('/client', clientRouter)
router.use('/product', productRouter)
router.use('/baking', bakingRouter)
router.use('/sales', salesRouter)
router.use('/mixers', bakingFacilityUnitsRouter)
router.use('/release', dispatchRouter)
router.use('/inPrice', individualPrices)
router.use('/finance', finance)
router.use('/financeCategories', financeCategories)

module.exports = router
