const { Router } = require('express')

const contragentRouter = require('./contragent.route')
const contragentTypeRouter = require('./contragentType.route')
const userRouter = require('./user.route')
const requestRouter = require('./request.route')
const clientRouter = require('./client.route')
const productRouter = require('./product.route')
const bakingRouter = require('./baking.route')
const salesRouter = require('./sales.route')
const bakingFacilityUnitsRouter = require('./bakeryFacilityUnits.route')
const dispatchRouter = require('./dispatch.route')
const individualPrices = require('./individualPrices.route')
const finance = require('./finance.route')
const financeCategories = require('./financeCategories.route')
const providers = require('./providers.route')
const productPurchaseRouter = require('./productPurchase.route')
const magazinesRouter = require('./magazines.route')
const debtTransferRouter = require('./debtTransfer.route')
const departPersonalRouter = require('./departPersonal.route')
const shiftAccountingRouter = require('./shiftAccounting.route')
const reportsRouter = require('./reports.route')
const factInputRouter = require('./factInput.route')
const overPriceRouter = require('./overPrice.route')
const providerGoodsRouter = require('./providerGoods.route')
const placeRouter = require('./place.route')
const adjustmentRouter = require('./adjustment.route')
const financeAccountRouter = require('./financeAccount.route')
const goodsCategories = require('./goodsCategories.route')
let router = Router()

router.use('/contragent', contragentRouter)
router.use('/contragentType', contragentTypeRouter)
router.use('/user', userRouter)
router.use('/requests', requestRouter)
router.use('/client', clientRouter)
router.use('/product', productRouter)
router.use('/baking', bakingRouter)
router.use('/sales', salesRouter)
router.use('/mixers', bakingFacilityUnitsRouter)
router.use('/release', dispatchRouter)
router.use('/inPrice', individualPrices)
router.use('/finance', finance)
router.use('/financeCategories', financeCategories)
router.use('/financeAccount', financeAccountRouter)
router.use('/providers', providers)
router.use('/productPurchase', productPurchaseRouter)
router.use('/magazines', magazinesRouter)
router.use('/debtTransfer', debtTransferRouter)
router.use('/departPersonal', departPersonalRouter)
router.use('/shiftAccounting', shiftAccountingRouter)
router.use('/reports', reportsRouter)
router.use('/factInput', factInputRouter)
router.use('/overPrice', overPriceRouter)
router.use('/providerGoods', providerGoodsRouter)
router.use('/goodsCategories', goodsCategories)
router.use('/place', placeRouter)
router.use('/adjustment', adjustmentRouter)

module.exports = router
